Gift-For-You-Project/gift-for-you-BE

src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/entity/User.java
src/main/java/com/giftforyoube/user/service/KakaoService.java

Refactor: Kakao 로그인 시나리오 테스트에 따른 로직 변경

---

src/main/java/com/giftforyoube/user/controller/UserController.java

Update: OAuth 로그인 Redirect URL 변경

---

src/main/java/com/giftforyoube/funding/entity/Funding.java
src/main/java/com/giftforyoube/global/config/RedisConfig.java
src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java

develop to feat/auth

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/dto/ApproveDonationResponseDto.java
src/main/java/com/giftforyoube/donation/dto/DonationRequestDto.java
src/main/java/com/giftforyoube/donation/dto/DonationResponseDto.java
src/main/java/com/giftforyoube/donation/dto/ReadyDonationRequestDto.java
src/main/java/com/giftforyoube/donation/dto/ReadyDonationResponseDto.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Feat: Kakaopay 단건 결제준비 기능 구현

---

src/main/java/com/giftforyoube/global/config/CorsConfig.java
src/main/java/com/giftforyoube/global/config/WebSecurityConfig.java
src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: CORS 설정 변경

---

src/main/java/com/giftforyoube/global/config/CorsConfig.java

Update: vercel URL 업데이트

---

src/main/java/com/giftforyoube/funding/controller/FundingController.java
src/main/java/com/giftforyoube/funding/dto/FundingResponseDto.java
src/main/java/com/giftforyoube/funding/entity/Funding.java
src/main/java/com/giftforyoube/funding/service/FundingService.java
src/main/java/com/giftforyoube/global/config/RedisConfig.java
src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java

style: Funding 리팩토링 (페이지네이션)

---

src/main/java/com/giftforyoube/funding/controller/FundingController.java
src/main/java/com/giftforyoube/funding/dto/FundingResponseDto.java
src/main/java/com/giftforyoube/funding/repository/FundingRepository.java
src/main/java/com/giftforyoube/funding/service/FundingService.java
src/main/java/com/giftforyoube/global/config/CorsConfig.java
src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/home/controller/HomeController.java

fix: CorsConfig - /api 삭제

---

src/main/java/com/giftforyoube/global/jwt/JwtUtil.java
src/main/java/com/giftforyoube/user/controller/UserController.java

Update: 배포 URL 업데이트

---

src/main/java/com/giftforyoube/donation/controller/DonationRestController.java
src/main/java/com/giftforyoube/donation/entity/Donation.java

Fix: user 맵핑 수정

---

src/main/java/com/giftforyoube/donation/dto/DonationInfoDto.java
src/main/java/com/giftforyoube/donation/entity/Donation.java
src/main/java/com/giftforyoube/donation/repository/DonationRepository.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Feat: fundingId별 결제 순위 조회 기능 구현
Feat: fundingId별 누적 결제 금액 조회 기능 구현

Feat: fundingId별 결제 순위 및 누적 결제 금액 조회 기능 구현

---

src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: social login redirect 주석 처리

Fix: social login redirect 주석 처리

---

src/main/java/com/giftforyoube/user/controller/UserController.java

Feat: social login response API 추가

Feat: social login response API 추가

---

src/main/java/com/giftforyoube/donation/controller/DonationRestController.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Refactor: 코드 1차 리팩토링 진행

---

src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: social login redirect 주석 재처리

Fix: social login redirect 주석 재처리

---

src/main/java/com/giftforyoube/donation/controller/DonationRestController.java

Fix: 후원 결제승인 후 redirect 변경

---

src/main/java/com/giftforyoube/donation/controller/DonationRestController.java

Fix: 후원 결제승인 후 redirect 재변경

---

src/main/java/com/giftforyoube/global/jwt/JwtUtil.java

Feat: JWT 쿠키 내 HTTPOnly 및 Secure 속성 추가

Feat: JWT 쿠키 내 HTTPOnly 및 Secure 속성 추가

---

src/main/java/com/giftforyoube/funding/controller/FundingController.java
src/main/java/com/giftforyoube/funding/repository/FundingRepository.java
src/main/java/com/giftforyoube/funding/service/FundingService.java

fix: pagenation size 6개로 수정 / status 삭제 / Query 추가

fix: pagenation size 6개로 수정 / status 삭제 / Query 추가

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/entity/Donation.java

Refactor: 코드 2차 리팩토링 진행

---

src/main/java/com/giftforyoube/global/exception/BaseResponse.java
src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/global/exception/ExceptionHandler.java
src/main/java/com/giftforyoube/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/giftforyoube/global/jwt/JwtAuthorizationFilter.java
src/main/java/com/giftforyoube/global/jwt/JwtUtil.java
src/main/java/com/giftforyoube/global/security/UserDetailsServiceImpl.java
src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/dto/DeleteRequestDto.java
src/main/java/com/giftforyoube/user/dto/GoogleUserInfoDto.java
src/main/java/com/giftforyoube/user/dto/KakaoUserInfoDto.java
src/main/java/com/giftforyoube/user/dto/LoginRequestDto.java
src/main/java/com/giftforyoube/user/dto/SignupRequestDto.java
src/main/java/com/giftforyoube/user/entity/User.java
src/main/java/com/giftforyoube/user/repository/UserRepository.java
src/main/java/com/giftforyoube/user/service/GoogleService.java
src/main/java/com/giftforyoube/user/service/KakaoService.java
src/main/java/com/giftforyoube/user/service/UserService.java

Refactor: user 관련 리팩토링 진행

---

src/main/java/com/giftforyoube/user/controller/UserRedirectController.java

Feat: UserRedirectController 추가

Feat: UserRedirectController 추가

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/user/controller/UserRedirectController.java
src/main/java/com/giftforyoube/user/controller/UserRedirectTestController.java

Feat: UserRedirectTestController 추가

Feat: UserRedirectTestController 추가

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Feat: fundingId 예외처리 및 clearFundingCaches() 적용

Feat: fundingId 예외처리 및 clearFundingCaches() 적용

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java

Fix: redirect 방법 변경

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java

Fix: redirect 방법 재변경(중간 발표용)

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/repository/DonationRepository.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Reverts Gift-For-You-Project/gift-for-you-BE#69

Revert "feat: 후원자 정보 리스트 조회 기능"

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/repository/DonationRepository.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

feat: 후원자 리스트 조회 기능

---

src/main/java/com/giftforyoube/notification/controller/MailController.java
src/main/java/com/giftforyoube/notification/dto/MailRequestDto.java
src/main/java/com/giftforyoube/notification/service/MailingService.java

feat : 회원가입시 이메일 검증

---

src/main/java/com/giftforyoube/notification/service/MailingService.java

fix : 알림 이메일 발송 받는사람 이메일 수정 (테스트용 이메일 제거)

fix : 알림 이메일 발송 받는사람 이메일 수정 (테스트용 이메일 제거)

---

src/main/java/com/giftforyoube/GiftForYouBeApplication.java
src/main/java/com/giftforyoube/donation/controller/DonationController.java
src/main/java/com/giftforyoube/donation/repository/DonationRepository.java
src/main/java/com/giftforyoube/donation/service/DonationService.java
src/main/java/com/giftforyoube/funding/entity/Funding.java
src/main/java/com/giftforyoube/notification/service/MailingService.java
src/main/java/com/giftforyoube/notification/service/NotificationService.java
src/main/java/com/giftforyoube/scheduler/Scheduler.java
src/main/java/com/giftforyoube/user/repository/UserRepository.java

merger : develop <- feat/message2

merger : develop <- feat/message2

---

src/main/java/com/giftforyoube/notification/service/MailingService.java
src/main/resources/templates/EmailTemplateDonation.html
src/main/resources/templates/EmailTemplateFundingSuccess.html
src/main/resources/templates/EmailTemplateTimeOut.html

feat : 알림 별 이메일 html 템플릿 (후원, 펀딩성공, 펀딩시간마감)

feat : 알림 별 이메일 html 템플릿 (후원, 펀딩성공, 펀딩시간마감)

---

src/main/java/com/giftforyoube/donation/service/DonationService.java

Feat: donation에 따른 fundingId별 currentAmount 업데이트

Feat: donation에 따른 fundingId별 currentAmount 업데이트

---

src/main/java/com/giftforyoube/donation/service/DonationService.java
src/main/java/com/giftforyoube/funding/entity/Funding.java

Feat: targetAmount 달성 시 펀딩 종료 기능 구현

Feat: targetAmount 달성 시 펀딩 종료 기능 구현

---

src/main/java/com/giftforyoube/donation/dto/ReadyDonationResponseDto.java

Fix: next_redirect_mobile_url 추가

Fix: next_redirect_mobile_url 추가

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/controller/UserRedirectController.java
src/main/java/com/giftforyoube/user/dto/SignupRequestDto.java
src/main/java/com/giftforyoube/user/entity/User.java
src/main/java/com/giftforyoube/user/repository/UserRepository.java
src/main/java/com/giftforyoube/user/service/GoogleService.java
src/main/java/com/giftforyoube/user/service/KakaoService.java
src/main/java/com/giftforyoube/user/service/UserService.java

Fix: phoneNumber 제외 및 isEmailNotificationAgreed 추가

Fix: phoneNumber 제외 및 isEmailNotificationAgreed 추가

---

src/main/java/com/giftforyoube/global/jwt/JwtUtil.java
src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: domain 수정

---

src/main/java/com/giftforyoube/global/jwt/JwtUtil.java

Fix: domain 재수정

---

src/main/java/com/giftforyoube/user/dto/SignupRequestDto.java

Fix: isEmailNotificationAgreed 주석 해제

Fix: isEmailNotificationAgreed 주석 해제

---

build.gradle
src/main/java/com/giftforyoube/donation/service/DonationService.java
src/main/java/com/giftforyoube/funding/service/CacheService.java
src/main/java/com/giftforyoube/funding/service/FundingService.java
src/main/java/com/giftforyoube/scheduler/Scheduler.java

Merge : Feat/funding

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/notification/service/MailingService.java
src/main/java/com/giftforyoube/notification/service/NotificationService.java

merge : develop <- signupMail 

---

src/main/java/com/giftforyoube/funding/repository/FundingRepository.java

fix : jpa쿼리 메소드 수정

---

src/main/java/com/giftforyoube/funding/repository/FundingRepository.java
src/main/java/com/giftforyoube/funding/service/FundingService.java

fix : 쿼리메소드 수정

---

src/main/java/com/giftforyoube/scheduler/Scheduler.java

fix : 스케줄러 시간 변경

---

src/main/java/com/giftforyoube/notification/service/MailingService.java
src/main/resources/templates/EmailTemplateSignup.html

feat : 검증 이메일 발송 시 html 적용

---

src/main/java/com/giftforyoube/funding/dto/FundingResponseDto.java

fix : 진행바 계산 로직 수정

---

src/main/java/com/giftforyoube/user/dto/DeleteRequestDto.java
src/main/java/com/giftforyoube/user/dto/LoginRequestDto.java
src/main/java/com/giftforyoube/user/dto/SignupRequestDto.java

Fix: 비밀번호 정규식 수정(유저 테스트 피드백 반영)

Fix: 비밀번호 정규식 수정(유저 테스트 피드백 반영)

---

src/main/java/com/giftforyoube/funding/dto/FundingCreateRequestDto.java

fix : createRequestDto 금액 타입 수정

fix : createRequestDto 금액 타입 수정

---

src/main/java/com/giftforyoube/notification/dto/NotificationResponseDto.java
src/main/java/com/giftforyoube/notification/service/NotificationService.java

feat : notificationResponseDto 생성시간 추가

feat : notificationResponseDto 생성시간 추가

---

src/main/java/com/giftforyoube/notification/dto/SubscribeDummyDto.java
src/main/java/com/giftforyoube/notification/service/NotificationService.java

style : notificationService javadoc

style : notificationService javadoc

---

src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: Kakao login 엔드 포인트 수정

---

src/main/java/com/giftforyoube/user/service/KakaoUserService.java

Fix: Kakao login redirect 수정

---

src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/service/GoogleUserService.java

Fix: Google login redirect 수정

---

src/main/java/com/giftforyoube/user/service/GoogleUserService.java
src/main/java/com/giftforyoube/user/service/KakaoUserService.java

Fix: Social login redirect 최종 업데이트

Fix: Social login redirect 최종 업데이트

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java

Fix: BaseResponseStatus 수정

---

src/main/java/com/giftforyoube/donation/dto/ReadyDonationDto.java
src/main/java/com/giftforyoube/donation/service/DonationService.java

Refactor: donation 코드 리팩토링

---

src/main/java/com/giftforyoube/global/jwt/filter/JwtAuthorizationFilter.java

Fix: JwtAuthorizationFilter 로직 변경

Fix: JwtAuthorizationFilter 로직 변경

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java

Fix: approveDonation 실패 시, fundingId 추가 전달

Fix: approveDonation 실패 시, fundingId 추가 전달

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java

Fix: 후원 랭킹 조회 HttpStatus 변경

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/global/jwt/util/JwtTokenUtil.java
src/main/java/com/giftforyoube/user/controller/UserController.java

Fix: user 주석 및 BaseResponseStatus 수정
Fix: token 유효시간 임시 만료(테스트용)

Fix: token 유효시간 임시 만료(테스트용) 외 1건

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java

Fix: BaseResponseStatus code 수정

Fix: BaseResponseStatus code 수정

---

src/main/java/com/giftforyoube/donation/service/DonationService.java
src/main/java/com/giftforyoube/user/service/GoogleUserService.java
src/main/java/com/giftforyoube/user/service/KakaoUserService.java
src/main/java/com/giftforyoube/user/service/UserService.java

Refactor: service 클래스 내 JavaDocs 추가 반영

Refactor: service 클래스 내 JavaDocs 추가 반영

---

src/main/java/com/giftforyoube/global/exception/BaseResponseStatus.java
src/main/java/com/giftforyoube/global/jwt/util/JwtTokenUtil.java
src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/service/UserService.java

Fix: token 유효시간 및 BaseResponseStatus 변경

Fix: token 유효시간 및 BaseResponseStatus 변경

---

src/main/java/com/giftforyoube/donation/controller/DonationController.java

Fix: BaseResponseStatus 추가 변경

---

src/main/java/com/giftforyoube/funding/dto/FundingResponseDto.java
src/main/java/com/giftforyoube/funding/service/CacheService.java

fix : dday계산 로직 수정

---

src/main/java/com/giftforyoube/user/controller/UserController.java
src/main/java/com/giftforyoube/user/dto/OauthLoginRequestDto.java
src/main/java/com/giftforyoube/user/dto/OauthUserInfoDto.java
src/main/java/com/giftforyoube/user/service/GoogleUserService.java
src/main/java/com/giftforyoube/user/service/KakaoUserService.java
src/main/java/com/giftforyoube/user/service/UserService.java

Refactor: social login 요청 메서드 변경 & Fix: 일부 메서드 및 로그 삭제 / 주석 수정

Refactor: social login 요청 메서드 변경 & Fix: 일부 메서드 및 로그 삭제 / 주석 수정
